# Site settings
title: Ruoxi (Anna) Shang
author:
  name: Ruoxi (Anna) Shang
  email: rxshang@uw.edu
description: > # this means to ignore newlines until "show_excerpts:"
  Ruoxi (Anna) Shang's personal website

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
plugins:
 - jekyll-feed
 - jekyll-seo-tag

theme: minima

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title
